name       : python-html5-parser
version    : 0.4.9
release    : 7
source     :
    - https://github.com/kovidgoyal/html5-parser/archive/v0.4.9.tar.gz : fe45fb846dd6e71049fcb776ac9f5ba6876eafc548f7d7604cf2ecbfb77ddeef
license    : Apache-2.0
component  : programming.python
summary    : Fast C based HTML 5 parsing for python 2 & 3
description: |
    A fast, standards compliant, C based, HTML 5 parser for python. Over thirty times as fast as pure python based parsers, such as html5lib.
builddeps  :
    - pkgconfig(python3)
    - python-beautifulsoup4 # check
    - python-chardet
    - python-lxml
rundeps    :
    - python-lxml
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
